name: project
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cached_network_image: ^3.2.1
  cloud_firestore: ^3.4.0
  firebase_auth: ^3.5.0
  firebase_core: ^1.20.0
  firebase_storage: ^10.3.3
  flutter:
    sdk: flutter

  freezed_annotation: ^2.1.0
  go_router: ^4.2.1
  json_annotation: ^4.6.0
  provider: ^6.0.3
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  freezed: ^2.1.0+1
  build_runner: ^2.2.0
  json_serializable: ^6.3.1

flutter:

  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
