name: project
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cached_network_image: ^3.2.1
  cloud_firestore: ^3.4.3
  crypto: ^3.0.2
  firebase_auth: ^3.6.2
  firebase_core: ^1.20.0
  firebase_storage: ^10.3.4
  flutter:
    sdk: flutter

  flutter_dotenv: ^5.0.2
  flutter_screenutil: ^5.5.3+2
  flutter_spinkit: ^5.1.0
  freezed_annotation: ^2.1.0
  go_router: ^4.2.7
  intl: ^0.17.0
  json_annotation: ^4.6.0
  logger: ^1.1.0
  lottie: ^1.4.1
  provider: ^6.0.3
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  freezed: ^2.1.0+1
  build_runner: ^2.2.0
  json_serializable: ^6.3.1

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - .env

  fonts:
    - family: Poppins-Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Poppins-SemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf
